var painless = require('../../assertion/painless')
var test = painless.createGroup('Test random/random')
var t = painless.assert

var random = require('../../../src/random/random')

test('should use Math.random as default PRNG', function () {
  t.is(random.get, Math.random)
})

test('should return the value generated by the provided PRNG', function () {
  var n = 0

  random.get = function () {
    return ++n % 2 ? 0 : 1
  }

  t.is(random(), 0)
  t.is(random(), 1)
  t.is(random(), 0)
  t.is(random(), 1)
  random.get = Math.random // reset
})
