#!/usr/bin/env node

var path = require('path');
var glob = require('../src/glob/globby');
var resolveCwd = require('../src/path/resolve-cwd');
var argv = require('../src/process/minimist')(process.argv.slice(2), {
  alias: {
    i: 'include'
  }
});

if (argv.include) {
  var include = resolveCwd(argv.include);
  if (!include) {
    throw new Error('Unable to find include ' + argv.include);
  }
  require(include);
}

process.argv.slice(2).forEach(function onEach(arg) {
  glob(arg, function onGLob(err, files) {
    files.forEach(function onFile(file) {
      require(path.resolve(process.cwd(), file));
    });
  });
});