// adopted from: figures <sindresorhus/figures>
// Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com) (MIT)
// Unicode symbols with Windows CMD fallbacks

module.exports =  {
  tick: '✔',
  cross: '✖',
  star: '★',
  square: '▇',
  squareSmall: '◻',
  squareSmallFilled: '◼',
  circle: '◯',
  circleFilled: '◉',
  circleDotted: '◌',
  circleDouble: '◎',
  circleCircle: 'ⓞ',
  circleCross: 'ⓧ',
  circlePipe: 'Ⓘ',
  circleQuestionMark: '?⃝',
  bullet: '●',
  dot: '․',
  line: '─',
  ellipsis: '…',
  pointer: '❯',
  pointerSmall: '›',
  info: 'ℹ',
  warning: '⚠',
  hamburger: '☰',
  smiley: '㋡',
  mustache: '෴',
  heart: '♥',
  arrowUp: '↑',
  arrowDown: '↓',
  arrowLeft: '←',
  arrowRight: '→',
  radioOn: '◉',
  radioOff: '◯',
  checkboxOn: '☒',
  checkboxOff: '☐',
  checkboxCircleOn: 'ⓧ',
  checkboxCircleOff: 'Ⓘ',
  questionMarkPrefix: '?⃝',
  wtick: '√',
  wcross: '×',
  wstar: '*',
  wellipsis: '...',
  wpointer: '>',
  wpointerSmall: '»',
  winfo: 'i',
  wwarning: '‼',
  wradioOn: '(*)',
  wradioOff: '( )',
  wcheckboxOn: '[×]',
  wcheckboxOff: '[ ]',
  wcheckboxCircleOn: '(×)',
  wcheckboxCircleOff: '( )',
  wquestionMarkPrefix: '？'
}
